stages:
  - test
  - lint

variables:
  GO111MODULE: "on"
  CI_DEBUG_TRACE: "true"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


linting-job:
  stage: lint
  image: golang:latest
  script:
    - rm -f /builds/foxstudent106270/task-2.3-holiday-bot.tmp/CI_SERVER_TLS_CA_FILE
    - export GOINSECURE=*
    - set +e
    - go install golang.org/x/lint/golint@latest
    - go install honnef.co/go/tools/cmd/staticcheck@latest
    - go vet ./...
    - staticcheck ./...
    - golint -set_exit_status ./...
    - export GOINSECURE=*
    - set +e

testing-job:
  stage: test
  image: golang:latest
  script:
    - rm -f /builds/foxstudent106270/task-2.3-holiday-bot.tmp/CI_SERVER_TLS_CA_FILE
    - export GOINSECURE=*
    - set +e
    - go test ./...
    - export GOINSECURE=*
    - set +e
